# Generated by Django 2.2 on 2021-02-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_manager_app', '0004_auto_20210212_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(verbose_name=['%m-%d-%Y']),
        ),
    ]
