# Generated by Django 2.2 on 2021-02-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_manager_app', '0007_auto_20210212_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(default='', null=True),
        ),
    ]
