# Generated by Django 2.2 on 2021-02-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_manager_app', '0008_auto_20210216_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
